fastlane_version "1.89.0"

default_platform :android

platform :android do
  before_all do
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  lane :screenshots do
    gradle(task: "assembleDebug assembleAndroidTest")
    screengrab(
            locales: ['nl-NL', 'en-US', 'de-DE', 'fr-FR', 'hu-HU', 'ru-RU', 'tr-TR', 'uk-UA'],
            clear_previous_screenshots: true
        )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do |options|
    gradle(task: "assembleRelease", flags: "-PkeyStore=#{options[:keystore]} -Ppassword=#{options[:password]}")
    supply
  end

  desc "Deploy a new beta version to the Google Play"
  lane :beta do |options|
    gradle(task: "assembleRelease", flags: "-PkeyStore=#{options[:keystore]} -Ppassword=#{options[:password]}")
    supply track: "beta"
  end


  after_all do |lane|
  end

  error do |lane, exception|
  end
end
